version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - APP_ID=cli_a8f726faa1aed00e
      - APP_SECRET=HLE1Y8pi4ff8MBcDMXoXfdgpg2Dvkq5V
      - AILY_APP_ID=spring_3426513189__c
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
